### ISSUE TITLE
Göra en ad aktiv efter att varit inaktiv

### ISSUE THREAD

**Issue by sumsarj** [dtekcth/tv.dtek.se#1]
Just nu, när man gör en ad inaktiv så är det inte möjligt att göra den aktiv igen (endast relevant så länge utgångsdatumet inte är passerat).
Vore najs om d6 till exempel ska dra upp en drinklista på TVn att kunna temporärt inaktivera övriga ads på TVn, utan att behöva ladda upp och göra om allt efteråt.

**Comment by emilhem** [comment]
Fixed with 420a97d
